### ISSUE TITLE
feature: support `darling(flatten)`

### ISSUE THREAD

**Issue by al8n** [TedDriggs/darling#254] opened 2023-09-08 14:01 UTC
Hi, thanks for the amazing crate!

May I ask about supporting `darling(flatten)`? It is a common use case, and some derive macros will share some common meta.

e.g.
```rust
// Mocked structures for demonstration.
#[derive(Debug, Default)]
pub(crate) struct Short;

#[derive(Debug, Default)]
pub(crate) struct Long;

#[derive(Debug, Default)]
pub(crate) struct Aliases;

#[derive(Debug, Default)]
pub(crate) struct Name {
    pub(crate) short: Short,
    pub(crate) long: Long,
    pub(crate) aliases: Aliases,
}

#[derive(Debug, FromDeriveInput)]
#[darling(attributes(mycrate))]
struct Foo {
    ident: Ident,
    vis: Visibility,
    #[darling(flatten)]
    name: Name,
    default: Option<bool>,
}

#[derive(Debug, FromDeriveInput)]
#[darling(attributes(mycrate))]
struct Bar {
    ident: Ident,
    vis: Visibility,
   
    #[darling(flatten)]
    name: Name,
    
    ...other fields
}
```

**Comment by cdecompilador** [comment] 2023-09-30 11:09
Yeah, and for `enums` it would be very useful, for example imagine a trait `Template` that gets its source from a file or from inline string literal

```rust
#[derive(Template)]
#[template(path = "./index.html")]
struct Foo;

#[derive(Template)]
#[template(source = "<ul><li>{{ self.0 }}</li></ul>")]
struct Bar(u32);
```

```rust
#[derive(Debug, FromDeriveInput)]
#[darling(attributes(template))]
struct TemplateInput {
    ident: Ident,
    
    #[darling(flatten)]
    template_source: TemplateSource
}

#[derive(Debug, Default)]
enum TemplateSource {
     Path(std::path::Path),
     Source(String)
}
```

And that using both at the same time throws an error

**Comment by TedDriggs** [comment] 2023-10-16 15:43
Duplicate of #146 - please continue this discussion there.

**Closed by TedDriggs** 2023-10-16 15:43 UTC
