### ISSUE TITLE
FromMeta attribute for value which can be simple flag or String.

### ISSUE THREAD

**Issue by chtotut** [TedDriggs/darling#77] opened 2019-05-03 19:27 UTC
Hi, I want to create attribute for:

```rust
#[derive(Test)]
pub struct Struct {
    #[test(value)]
    a: u8,
    #[test(value = "some expression")]
    b: u8,
}
```

value can be simple flag or String.
Is it possible?

**Comment by TedDriggs** [comment] 2019-05-06 22:30
Would the type of `value` be an enum? If so, then this feels like a duplicate of #63, which would add support for associating the basic form of an enum with a specific variant.

Otherwise, you can implement this yourself without too much difficulty by filling in the following:

```rust
impl FromMeta for YourValue {
    fn from_word() -> darling::Result<Self> {}
    fn from_str(s: &str) -> darling::Result<Self> {}
}
```

**Comment by chtotut** [comment] 2019-05-07 07:30
No the value is something like `sun::Expr`, `sun::Type`, represents as string.

**Closed** 2019-05-07 07:32 UTC
Labels: question
